[2018-01-17 00:15:05,663] - AccountPrivacy:_visible_css_selectop] - INFO: Cause of error.. Traceback (most recent call last):
  File "E:\operating\PageWeb\WebEven\AccountPrivacy.py", line 227, in _visible_css_selectop
    EC.visibility_of_element_located((By.CSS_SELECTOR, locator)))
  File "E:\Program Files\Python36\lib\site-packages\selenium\webdriver\support\wait.py", line 80, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: 


[2018-01-17 00:15:11,919] - AccountPrivacy:_visible_css_selectop] - INFO: Cause of error.. Traceback (most recent call last):
  File "E:\operating\PageWeb\WebEven\AccountPrivacy.py", line 227, in _visible_css_selectop
    EC.visibility_of_element_located((By.CSS_SELECTOR, locator)))
  File "E:\Program Files\Python36\lib\site-packages\selenium\webdriver\support\wait.py", line 80, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: 


[2018-01-17 00:15:17,780] - AccountPrivacy:sign_user_login] - INFO: Cause of error.. Traceback (most recent call last):
  File "E:\operating\PageWeb\WebEven\AccountPrivacy.py", line 129, in sign_user_login
    driver.find_element_by_css_selector("#J_tel").send_keys(account)
  File "E:\Program Files\Python36\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 509, in find_element_by_css_selector
    return self.find_element(by=By.CSS_SELECTOR, value=css_selector)
  File "E:\Program Files\Python36\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 855, in find_element
    'value': value})['value']
  File "E:\Program Files\Python36\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 308, in execute
    self.error_handler.check_response(response)
  File "E:\Program Files\Python36\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 194, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"css selector","selector":"#J_tel"}
  (Session info: chrome=63.0.3239.132)
  (Driver info: chromedriver=2.34.522940 (1a76f96f66e3ca7b8e57d503b4dd3bccfba87af1),platform=Windows NT 10.0.16299 x86_64)


[2018-01-17 00:15:18,356] - AccountPrivacy:sign_switching_logon] - INFO: Cause of error.. Traceback (most recent call last):
  File "E:\operating\PageWeb\WebEven\AccountPrivacy.py", line 110, in sign_switching_logon
    sign_user_login(account, password)
  File "E:\operating\PageWeb\WebEven\AccountPrivacy.py", line 129, in sign_user_login
    driver.find_element_by_css_selector("#J_tel").send_keys(account)
  File "E:\Program Files\Python36\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 509, in find_element_by_css_selector
    return self.find_element(by=By.CSS_SELECTOR, value=css_selector)
  File "E:\Program Files\Python36\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 855, in find_element
    'value': value})['value']
  File "E:\Program Files\Python36\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 308, in execute
    self.error_handler.check_response(response)
  File "E:\Program Files\Python36\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 194, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"css selector","selector":"#J_tel"}
  (Session info: chrome=63.0.3239.132)
  (Driver info: chromedriver=2.34.522940 (1a76f96f66e3ca7b8e57d503b4dd3bccfba87af1),platform=Windows NT 10.0.16299 x86_64)


[2018-01-17 00:33:23,635] - AccountPrivacy:_visible_css_selectop] - INFO: Cause of error.. Traceback (most recent call last):
  File "E:\operating\PageWeb\WebEven\AccountPrivacy.py", line 232, in _visible_css_selectop
    EC.visibility_of_element_located((By.CSS_SELECTOR, locator)))
  File "E:\Program Files\Python36\lib\site-packages\selenium\webdriver\support\wait.py", line 80, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: 


[2018-01-17 00:33:24,118] - AccountPrivacy:sign_switching_logon] - INFO: Cause of error.. NoneType: None

[2018-01-17 00:37:08,878] - AccountPrivacy:_visible_css_selectop] - INFO: Cause of error.. Traceback (most recent call last):
  File "E:\operating\PageWeb\WebEven\AccountPrivacy.py", line 232, in _visible_css_selectop
    EC.visibility_of_element_located((By.CSS_SELECTOR, locator)))
  File "E:\Program Files\Python36\lib\site-packages\selenium\webdriver\support\wait.py", line 80, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: 


[2018-01-17 00:37:09,378] - AccountPrivacy:sign_switching_logon] - INFO: Cause of error.. NoneType: None

[2018-01-17 00:39:10,514] - AccountPrivacy:_visible_css_selectop] - INFO: Cause of error.. Traceback (most recent call last):
  File "E:\operating\PageWeb\WebEven\AccountPrivacy.py", line 232, in _visible_css_selectop
    EC.visibility_of_element_located((By.CSS_SELECTOR, locator)))
  File "E:\Program Files\Python36\lib\site-packages\selenium\webdriver\support\wait.py", line 80, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: 


[2018-01-17 00:39:11,067] - AccountPrivacy:sign_switching_logon] - INFO: Cause of error.. NoneType: None

